### ISSUE TITLE
403 - "Token is missing required scope. Use one of: ExternalSyntheticIntegration"

### ISSUE THREAD

**Issue by peba63** [Dynatrace/dynatrace-api#10]
Hi Wolfgang,

I have studied Your Code, and adapted it to my Dynatrace instance and api-token.

When I do a POST i get the below response back : 

{
    "error": {
        "code": 403,
        "message": "Token is missing required scope. Use one of: ExternalSyntheticIntegration"
    }
}

Can't find any documentation on this anywhere.

Please advice

/Per Bastholm - Red Ocean DK.

**Comment by Stephan-Berlin** [comment]
As mentioned in this article, you need to participate at the EAP. Then you are able to add the scope "Send external synthetic data to Dynatrace".
