### ISSUE TITLE
The property 'scheduleIntervalInSeconds' must not be null or empty

### ISSUE THREAD

**Issue by BraydenNeale** [Dynatrace/dynatrace-api#11]
`py externalSyntheticExample.py
Synthetic request - Response time:0.658543s Status code:200 Success:True
<Response [400]>
{"error":{"code":400,"message":"The property 'scheduleIntervalInSeconds' must not be null or empty."}}`

I have only changed:
YOUR_DT_API_URL
YOUR_DT_API_TOKEN

payload var visibly contains:
`"scheduleIntervalInSeconds": 60`

python3.6.5

**Comment by sagerobert** [comment]
@BraydenNeale How did you solved this issue?

**Comment by BraydenNeale** [comment]
Hey @sagerobert 

I was testing against a Dev build at the time.
The `scheduleIntervalInSeconds` property was moved from `testResults` to `tests` in an API change in 1.150.
I have now created a pull request for this.

**Comment by sagerobert** [comment]
@BraydenNeale Thanks for the info, I figured it out by trail-and-error :-)

**Comment by myieye** [comment]
Closed due to inactivity.
