### ISSUE TITLE
TypeError: must be unicode, not str

### ISSUE THREAD

**Issue by thegreatkb** [Dynatrace/dynatrace-api#19]
I am using Python 2.7.5 & Getting error while executing configurations/save.py

[dynatrace@xxxxx63 ~]$ python save.py
managementZones save list: 200
-1171957049078145000

Traceback (most recent call last):
  File "save.py", line 34, in <module>
    main()
  File "save.py", line 31, in main
    saveList('managementZones')
  File "save.py", line 25, in saveList
    save('/api/config/v1/' + list_type + '/', entry['id'], tr.json())
  File "save.py", line 15, in save
    text_file.write("%s" % json.dumps(content))
TypeError: must be unicode, not str

**Comment by myieye** [comment]
Closed due to inactivity
