### ISSUE TITLE
Activegate Proxy not working

### ISSUE THREAD

**Issue by kassimila** [Dynatrace/dynatrace-api#37]
Trying to use the port plugin module. I'm getting an error when attempting to connect to the API using the plugin. Our activegates use a proxy to connect out to the SaaS solution, there does not appear to be a way to add this proxy to the configuration.

**Comment by kassimila** [comment]
Bump

**Comment by JoelStuart** [comment]
Hi team, an option that worked for me was using the REST API on the ActiveGate to send results. 

Requires that the REST API on the ActiveGate is enabled (or another AGs it could reach).

And then sending the test results through ActiveGate REST - with Tenant URL as:
https://localhost:9999/e/<tenantID>

**Comment by dlopes7** [comment]
Please use the latest version of the port extension @kassimila, it has proxy support now. Fixed in https://github.com/Dynatrace/dynatrace-api/pull/38
