### ISSUE TITLE
Ping and Port extensions continually open a new problem every hour.

### ISSUE THREAD

**Issue by APMGitHub** [Dynatrace/dynatrace-api#59]
In the event a problem is opened by the ping and port extensions which lasts more than 1 hour, the extension closes the problem and opens a new one.
As a result, if a problem is open for 24 hours you are likely to see 24 problems generated, and if we have alerts configured that equates to 24 alerts sent in a day for the same problem.
The extensions should only alert once for one problem and keep the problem open until it is resolved.

**Comment by myieye** [comment]
Thanks for reaching out! This is something we're aware.
@dlopes7 what's the current status of this?

**Comment by dlopes7** [comment]
Use a frequency smaller than 15 minutes for now. I will eventually expose the logic we are using to the extensions themselves (instead of dtapi) and you will be able to modify the code to do event repetition if you would like, but we won't implement it.

**Comment by APMGitHub** [comment]
> Use a frequency smaller than 15 minutes for now. I will eventually expose the logic we are using to the extensions themselves (instead of dtapi) and you will be able to modify the code to do event repetition if you would like, but we won't implement it.

I have tried a frequency of 10 already and the issue persists.

**Comment by dlopes7** [comment]
@myieye I made a pull request that changes the way we create an event ID in `dt-api`

Basically, there is no state being kept at all there anymore, if we have a problem, we always send the same test ID. This will make sure that the same problem remains opened as long as the test fails.

I have also added the parameter for failure_count for all extensions to keep them in sync with one another, and they are all version 1.011 now.

@APMGitHub Please use version 1.011 once it is merged.

**Comment by dlopes7** [comment]
FYI, this has been validated, here is a ping outage that has been opened for almost 3 days


![image](https://user-images.githubusercontent.com/10208081/119240679-a74ea580-bb27-11eb-92e8-7d611ca6a1b1.png)
