### ISSUE TITLE
Getting Error(No module named 'dynatrace.environment_v1') when I add endpoint on Ping plugin

### ISSUE THREAD

**Issue by tushargks** [Dynatrace/dynatrace-api#67]
Getting **Error(No module named 'dynatrace.environment_v1')** when I add endpoint on Ping plugin: 
Not sure if i am doing something wrong, Please advise ASAP

 Ping
Version: 1.012 Type: ActiveGate extension Id: custom.remote.python.thirdparty_ping
![ping extension error](https://user-images.githubusercontent.com/77305331/128425436-61a991e1-7f78-45fd-a529-93b921f6c285.png)

**Comment by myieye** [comment]
@dlopes7 Could you help out here maybe?

**Comment by tushargks** [comment]
@myieye @dlopes7 

The port check extension is working fine on the same cluster, but seeing above error for Ping extension, could you please check and help me at the earliest 

Thanks

**Comment by myieye** [comment]
I don't know a ton about extensions, but if it can't find a module, I'd assume that it's not deployed on the ActiveGate properly.
Did you deploy the right zip file? Is it maybe corrupted?
![image](https://user-images.githubusercontent.com/12587509/128673408-88f0024b-8c6d-4d65-90cc-c1cf359a2510.png)

**Comment by tushargks** [comment]
@myieye 

I am doing it on Linux server and yes the Extension is deployed on the Activegate under path:
"/opt/dynatrace/remotepluginmodule/plugin_deployment"  

Today I tried to deploy the same extension on different AG on the same cluster and it works, looks like its issue with the Active Gate, is there any location i can look for the logs on the not working AG? Weird part is the other extensions are working on this AG

**Comment by myieye** [comment]
Here's the troubleshooting page. Right at the top it tells you where to find logs: https://www.dynatrace.com/support/help/extend-dynatrace/extensions/troubleshooting/troubleshoot-extensions/

**Comment by myieye** [comment]
`dynatrace.environment_v1` is packaged in the extension for both the ping and port extensions.
![image](https://user-images.githubusercontent.com/12587509/128826546-b84f5fa0-3544-4b56-ae33-32baa4472a2c.png)

I'm assuming you tried redownloading it and redeploying it on the cluster and AG?

**Comment by tushargks** [comment]
@myieye 
yes i re done all the steps but same results, not sure how to proceed from here

**Comment by myieye** [comment]
I've reached out to several developers now. Will let you know when I learn anything.

**Comment by dlopes7** [comment]
@tushargks this is likely an issue with different extensions using the same `dynatrace` package in different versions.

Make sure you have all synthetic extensions (ping, port, dns) on the latest version on that AG, the latest version uses the same `dynatrace` package version

**Comment by tushargks** [comment]
@dlopes7 

This works, thanks you! 
Could you let me know what directory i can find the plugin logs, i did check under /var/log/dynatrace but no plugin directory available to check the logs

**Comment by myieye** [comment]
@dlopes7 Thanks for the help!!

@tushargks As stated on the [troubleshooting page](https://www.dynatrace.com/support/help/extend-dynatrace/extensions/troubleshooting/troubleshoot-extensions/), the logs should be in `/var/lib/dynatrace/remotepluginmodule/log/remoteplugin`

**Comment by myieye** [comment]
Closing as @tushargks's problem has been solved by using the most current version of all extensions so that there aren't conflicting dependency versions.
