### ISSUE TITLE
ping monitoring from multiple Locationg

### ISSUE THREAD

**Issue by tushargks** [Dynatrace/dynatrace-api#69]
@myieye and @dlopes7

I am trying to monitor the ping availability of the network device from different Locations, 

For example if I deploy ping extension on 2 different Environmental ActiveGates located in different datacenters , Is there a way i can monitor the ping response of the device from both the location ActiveGates in a single monitor, like how we do synthetic single url monitoring from multiple ActiveGate locations 

Was looking for if there a way we can add/choose multiple Active Gates while adding the ping end point as shown in the attached screen shot or if we add 2 different ping monitors for the same device choosing 2 different Active gates will both the monitors  ActiveGate reports to the single ping monitor or it creates 2 different ping monitors  

![ping AG](https://user-images.githubusercontent.com/77305331/130125543-d930ea91-5006-4a8d-8a61-692ddb7c6f76.png)
Thank You!

**Comment by myieye** [comment]
@tushargks Having multiple extensions push data to the same third-party synthetic monitor is not supported by the current implementation.

A third-party monitor instance is identified by a combination of the `engine_name` and `test_id`. To update the extension for your needs you could either:

1. Use the "Synthetic monitor name" as the `test_id` or
2. Create an extra "Test Id" field/property.

Relevant code:
https://github.com/Dynatrace/dynatrace-api/blob/b5621daa9d49987459f5e25e5e18981c87921629/third-party-synthetic/active-gate-extensions/extension-third-party-ping/src/ping_extension.py#L67
(`self.activation.entity_id` is an id unique to each extension instance)

**Comment by tushargks** [comment]
@myieye 

Thank you ! for the information

Could you let me know any example on how I can explore these 2 options

thank you!

**Comment by myieye** [comment]
@tushargks I think the best I can offer you is the extensions tutorial: https://www.dynatrace.com/support/help/extend-dynatrace/extensions/activegate-extensions/write-your-first-activegate-plugin/

Ultimately, the code changes would be very minimal, but I don't have an example for you.
